apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx-dep-app
spec:
  replicas: 6
  
  selector:
    matchLabels:
      env: prod  # this has to match with below labels
  
  template:
    # from creating a pod
    metadata:
      name: nginx-2
      labels:
        env: prod  # this has to match with matchLabels
    spec:
      containers:
        - name: nginx
          image: nginx

