apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-deployment
  name: task-deployment
  namespace: task
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: task-deployment
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        env:
          - name: MY_GREETING
            valueFrom:
              configMapKeyRef:
                key: greeting
                name: task-cm
        command: ["sh", "-c"]
        args: ["env; sleep 3600"]
        